### ISSUE TITLE
communicate with the customer to get more information about the requirement

### ISSUE THREAD

**Issue by jiyuhan** [uiowa-cs-5800-0001-fall-2017/Scratchat#4]

**Comment by utsab17** [comment]
any idea on how to work on this?

**Comment by ambroseaaron** [comment]
I'll have to set up a meeting with either the professor or ta and just ask him more about the project. If theres anything specific you guys want to know just let me know

**Comment by ruihaoxie** [comment]
So the customers are our professor and TA not the user of our project? I just want to make sure if we need to have some part in our project to handle the user feedback or something like that.

**Comment by jiyuhan** [comment]
aaron brought back some positive/important info and this is closed.
